name: Publish epaper
on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:
jobs:
  build:
    name: Publish epaper
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.0'
      - name: Install requirements 
        run: pip install pyrogram==2.0.106 tgcrypto requests bs4
      - name: Check for showstoppers
        run: curl -s ${{ secrets.EPAPER }} | sh
