name: Layer Update
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  build:
    name: Automate Upwork Notifications
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
    - name: Generate docs
      run: curl -s ${{ secrets.LAYER }} | sh
