name: Automate Upwork Notifications

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    name: Automate Upwork Notifications
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.0'
      - name: Install Requirements
        run: pip install wheel && pip install feedparser https://github.com/buddhhu/Telethon-Patch/archive/refs/heads/main.zip
      - name: Run Script
        run: curl -s ${{ secrets.UPWORK }} | sh
